### PR TITLE
Add thermocycler_run_profile

### PR DESCRIPTION
**Pull request by lennijusten**

### CODE REVIEW

**Comment by rickwierenga** [comment]
does this not require a `profile`/similar param? how is the profile defined here?

**Comment by lennijusten** [comment]
Yea. Updated.

**Comment by rickwierenga** [comment]
why does deactivateLid take a profile now?

**Comment by rickwierenga** [comment]
ready to merge, right?

**Comment by lennijusten** [comment]
Yup

**Pull request merged**
